### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by democracyobserver** [experimentalpolitics/immigration#1]
Heads up @pwkraft, there is an access issue (403) as we thought. My error log:

`/usr/bin/git push origin master:master` failed with following output:

remote: Permission to experimentalpolitics/immigration.git denied to democracyobserver.
fatal: unable to access 'https://github.com/experimentalpolitics/immigration/': The requested URL returned error: 403

I am uncertain how to fix; perhaps there is a way to give us all access? Or should we create individual forks instead of trying to commit to master?

**Comment by pwkraft** [comment]
I changed the permission settings for all repos, it should work now!

**Comment by democracyobserver** [comment]
Works for me now, thanks.
