### ISSUE TITLE
Update appendix / additional analyses

### ISSUE THREAD

**Issue by JasonNeumeyer** [experimentalpolitics/immigration#15]
- [x] sample demographics (in tables)
- [x] balance checks (in graphs): https://cran.r-project.org/web/packages/cobalt/vignettes/cobalt_A0_basic_use.html
- [x] describe demographics and balance checks 
- [ ] attitude uncertainty as moderator?
- [ ] additional robustness checks or exploratory analyses?

**Comment by pwkraft** [comment]
We'll leave the following two points open for future revisions / iterations:
- attitude uncertainty as moderator?
- additional robustness checks or explanatory analyses?
