### ISSUE TITLE
Theory / Lit review

### ISSUE THREAD

**Issue by pwkraft** [experimentalpolitics/immigration#7]
Patrick:
- [x] scrap the pandoc magic
- [x] move the current manuscript to Rmd 
- [x] outline argument for the manuscript
- [x] identify gaps in the literature / open question / puzzle
- [x] write the introduction section
- [x] write section 2.1: why corrections often fail

Taraleigh:
- [x] go through .bib and add notes to papers
- [x] add papers that are not in .bib yet
- [x] write section 2.3: media choice...
- [x] take over section 2.2 when A&SY are done

Next steps for literature review:
- [x] identify main theoretical approaches
- [x] discuss recent papers central to the argument

Amanda & Shin Young:
- [x] add notes for 2.2: differentiating factual beliefs

**Comment by tdunc17** [comment]
Pandoc Magic is sorcery @pwkraft

**Comment by tdunc17** [comment]
I am going to look through the two papers we talked about today (Brashier and Guess) to see how they can fit with our paper.
